version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 064131780653.dkr.ecr.us-east-1.amazonaws.com
      - BACKEND_URI=064131780653.dkr.ecr.us-east-1.amazonaws.com/taskflow-backend
      - FRONTEND_URI=064131780653.dkr.ecr.us-east-1.amazonaws.com/taskflow-frontend
      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION

  build:
    commands:
      - echo Building backend image...
      - docker build -t $BACKEND_URI:$IMAGE_TAG ./backend
      - docker tag $BACKEND_URI:$IMAGE_TAG $BACKEND_URI:latest

      - echo Building frontend image...
      - docker build -t $FRONTEND_URI:$IMAGE_TAG ./frontend
      - docker tag $FRONTEND_URI:$IMAGE_TAG $FRONTEND_URI:latest

  post_build:
    commands:
      - echo Pushing images to ECR...
      - docker push $BACKEND_URI:$IMAGE_TAG
      - docker push $BACKEND_URI:latest
      - docker push $FRONTEND_URI:$IMAGE_TAG
      - docker push $FRONTEND_URI:latest
      - echo Writing image definitions...
      - printf '[{"name":"backend","imageUri":"%s"}]' $BACKEND_URI:$IMAGE_TAG > imageDefinitions.json

artifacts:
  files:
    - imageDefinitions.json